language: python
python:
  - '3.7'
script: python manage.py -h
deploy:
  provider: pypi
  user: wuyue
  password:
    secure: wD2Ei9BOmfNnTtMyLrt8rJUbhO6i1ftUZPojCc8luCAbDyeCar0eHAQf5f5UUL/iMnl8YcAsEW3dsJwyg06ITFGmQd+66k972D8qpCoBSANS0M6kge8MhKx3uHodvSJOBXvH5Xe6B4pGhtDsLJwSgF9FWQqtE2aR4k+yiuGuv17FwAbv5hy7tRgGUFZvXFzG3PpI1KPyvu3i/jmqS4JDdslh9TkU5GUoLuRoj2LFEwh7twCFwili//+yfcBxdqP4eDFWvEyZLgUC4QSlca+8EpN+ZiiPPChW8+0F7f3U1wLTXBKQWzo7ZlmzYwlhdaxMCGk845eJTo6VB90XO4juZ/60qSu8RHIHyjwjpYL2asue+hSCqu/qnBgOqDY4ShKmLEg4KT41WwkumqBj9zK055nA+0e6ysqKEx6EpunvCyc5Tr+4+3b/fhh86r+Bf5BOTXY8TmzydOKA1wYwgH8rGwbD6DWz2RGSTY3NCAKhqZyxR0IY+ozx1HBorrD7ki9iDiCXJ6Yg9hzr6C92ipfuewMKZkzziteQZgzZlANvwzZ9icCXxa4FFfUpD4q5Gdl/idf7Yu6ToU+Vdm22yaHckyr5PNydmERqxXHcYe11AtWvesVHLHuAcNM0/wLo0bzETS+RU3PgXGZL2nrEBOZ7GW2C206b0TezDePTu5wvHFY=
  skip_existing: true
  skip_cleanup: true
  on:
    tag: true
    all_branches: true
branches:
  except:
    - develop
    - master
