# Generated by Django 2.2.6 on 2019-10-23 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20191014_0953'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Port')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('hosts', models.ManyToManyField(to='asset.Host', verbose_name='Hosts')),
                ('service_type', models.ForeignKey(on_delete=models.Model, to='service.ServiceType', verbose_name='serviceType')),
            ],
            options={
                'verbose_name': 'Service Task',
                'verbose_name_plural': 'Service Tasks',
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceConfig',
        ),
    ]
