# Generated by Django 2.2.6 on 2019-10-23 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191023_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Valid'),
        ),
        migrations.CreateModel(
            name='ServiceTaskRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('service_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceTask', verbose_name='serviceTask')),
            ],
            options={
                'verbose_name': 'Service Task Record',
                'verbose_name_plural': 'Service Task Records',
            },
        ),
    ]
