# Generated by Django 2.2.6 on 2019-10-23 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20191023_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetaskrecord',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.CreateModel(
            name='ServiceTaskResponese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('service_task_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceTaskRecord', verbose_name='serviceTaskRecord')),
            ],
            options={
                'verbose_name': 'Service Task Response',
                'verbose_name_plural': 'Service Task Responses',
            },
        ),
    ]
