# Generated by Django 2.2.6 on 2019-10-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20191014_0953'),
        ('service', '0005_servicetaskresponese_host'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceTaskResponese',
            new_name='ServiceTaskResponse',
        ),
    ]
