# Generated by Django 2.2.6 on 2019-10-11 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('client_dir', models.CharField(default='/opt/frp/bin/frpc', max_length=255, verbose_name='clientDir')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
            ],
            options={
                'verbose_name': 'Frp Client',
                'verbose_name_plural': 'Frp Clients',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('server_dir', models.CharField(default='/opt/frp/bin/frps', max_length=255, verbose_name='serverDir')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
            ],
            options={
                'verbose_name': 'Frp Server',
                'verbose_name_plural': 'Frp Servers',
            },
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Server', verbose_name='Server')),
            ],
            options={
                'verbose_name': 'Server Config',
                'verbose_name_plural': 'Server Configs',
            },
        ),
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client Config',
                'verbose_name_plural': 'Client Configs',
            },
        ),
    ]
