# Generated by Django 2.2.6 on 2019-10-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SshKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('ssh_key', models.FileField(upload_to='./ssh_key', verbose_name='sshKey')),
            ],
            options={
                'verbose_name': 'Ssh Key',
                'verbose_name_plural': 'Ssh Keys',
            },
        ),
    ]
