# Generated by Django 2.2.6 on 2019-10-14 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_sshkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ssh_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.SshKey', verbose_name='sshKey'),
        ),
    ]
