# Generated by Django 2.2.6 on 2019-10-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20191014_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.IntegerField(choices=[(0, 'READY'), (1, 'ONLINE'), (2, 'OFFLINE')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='host',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Valid'),
        ),
    ]
