# Generated by Django 2.2.6 on 2019-10-24 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0004_auto_20191014_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('args', models.TextField(verbose_name='Args')),
                ('valid', models.BooleanField(default=True, verbose_name='Valid')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('hosts', models.ManyToManyField(to='asset.Host', verbose_name='Hosts')),
            ],
            options={
                'verbose_name': 'Ansible Task',
                'verbose_name_plural': 'Ansible Tasks',
            },
        ),
        migrations.CreateModel(
            name='AnsibleTaskRecord',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('ansible_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answeb.AnsibleTask', verbose_name='ansibleTask')),
            ],
            options={
                'verbose_name': 'Ansible Task Record',
                'verbose_name_plural': 'Ansible Task Records',
            },
        ),
        migrations.CreateModel(
            name='AnsibleTaskResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('ansible_task_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answeb.AnsibleTaskRecord', verbose_name='ansibleTaskRecord')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Host', verbose_name='Host')),
            ],
            options={
                'verbose_name': 'Ansible Task Response',
                'verbose_name_plural': 'Ansible Task Responses',
            },
        ),
    ]
