# Generated by Django 2.2.6 on 2019-10-24 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('answeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletask',
            name='module',
            field=models.CharField(
                default='shell', max_length=255, verbose_name='Module'),
            preserve_default=False,
        ),
    ]
