# Generated by Django 2.2.6 on 2019-10-24 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('answeb', '0002_ansibletask_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletaskresponse',
            name='status',
            field=models.CharField(
                default='success', max_length=255, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
